### ISSUE TITLE
Global variables are not safe.

### ISSUE THREAD

**Issue by hishnash** [virtzilla/Paw-jq-JSON-processor-DynamicValue#2]
It looks like you are using a global variable for the `output`

https://github.com/virtzilla/Paw-jq-JSON-processor-DynamicValue/blob/master/jq.js#L10

While this looks ok in the preview it does not work when being run.
The extension will be loaded once even if there are multiple instances of the DV. It would be better if kept this data local to the DV class and passed it back inside the callback.

In addition i noticed when an error occurred it returned the error string. The normal behavior in paw it to return null and call ``console.error(msg)`

**Comment by virtzilla** [comment]
Just committed 2016051201 which contains the following changes:

Removed the global output variable and now use a callback to return the results from jq.

Added a check on the results from jq. If there an error it will return null to paw and direct the error output to console.error. Fairly basic and rudimentary in approach (and may not catch all), but it serves to catch the most common errors around jq input strings.
